# This is used to run Huey Tasks
#
FROM ubuntu:focal

RUN apt-get -y update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip python3-dev
ENV PYTHONIOENCODING=utf-8
RUN pip3 install --upgrade pip

COPY app/ /app
WORKDIR /app
RUN pip3 install -r huey-requirements.txt

COPY run_app.py /
WORKDIR /
ENTRYPOINT ["python3"]
CMD ["/opt/miniconda3/bin/huey_consumer.py","--verbose","app.tasks.get_similar.huey"]
